name: 'Setup VSWhere.exe'
description: 'Goes and downloads 2.7.1 VSWhere.exe as CLI tool and puts it into the path'
author: 'Warren Buckley'
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'download'
  color: 'purple'

